import type { RegionConfig } from "./types";

export const dach: RegionConfig = {
  id: "dach",
  name: "Germany, Austria & Switzerland",
  flag: "🇩🇪",
  covers: "Germany, Austria, Switzerland (Lebenslauf)",
  docName: "Lebenslauf (CV)",
  paper: "A4",
  dateFormat: "MM.YYYY",
  maxPages: 3,
  idealPages: 2,
  languageScale: "cefr",
  fields: {
    photo: "recommended",
    address: "recommended",
    dateOfBirth: "recommended",
    gender: "hidden",
    maritalStatus: "optional",
    nationality: "optional",
    religion: "hidden",
    nicNumber: "hidden",
    passportNumber: "hidden",
    visaStatus: "hidden",
    workAuthorization: "optional",
    drivingLicense: "optional",
    noticePeriod: "optional",
  },
  fieldNotes: {
    photo: "A professional photo is still customary, though legally optional.",
  },
  sections: [
    "personalDetails",
    "summary",
    "experience",
    "education",
    "languages",
    "skills",
    "certifications",
    "projects",
    "interests",
    "references",
    "declaration",
  ],
  sectionLabels: {
    personalDetails: "Persönliche Daten / Personal Details",
    summary: "Profile",
    experience: "Berufserfahrung / Work Experience",
    education: "Ausbildung / Education",
    languages: "Sprachkenntnisse / Languages",
    declaration: "Ort, Datum, Unterschrift",
  },
  references: { mode: "on-request" },
  declarationDefault: "",
  defaultTemplate: "modern",
  tips: [
    "A tabular, reverse-chronological layout is expected.",
    "Explain gaps in your timeline — German recruiters check for them.",
    "Finish with place, date and your signature.",
    "Rate languages on the CEFR scale (A1–C2).",
  ],
};
