import type { RegionConfig } from "./types";

export const europe: RegionConfig = {
  id: "eu",
  name: "Europe (Europass)",
  flag: "🇪🇺",
  covers: "France, Netherlands, Italy, Spain, Nordics, Poland and other EU countries",
  docName: "CV",
  paper: "A4",
  dateFormat: "MM/YYYY",
  maxPages: 3,
  idealPages: 2,
  languageScale: "cefr",
  fields: {
    photo: "optional",
    address: "optional",
    dateOfBirth: "optional",
    gender: "hidden",
    maritalStatus: "hidden",
    nationality: "optional",
    religion: "hidden",
    nicNumber: "hidden",
    passportNumber: "hidden",
    visaStatus: "hidden",
    workAuthorization: "optional",
    drivingLicense: "optional",
    noticePeriod: "optional",
  },
  fieldNotes: {
    photo: "Common in France, Belgium, Spain and Italy; avoid for the Netherlands and Nordics.",
  },
  sections: [
    "summary",
    "experience",
    "education",
    "languages",
    "skills",
    "certifications",
    "projects",
    "interests",
    "personalDetails",
    "references",
    "declaration",
  ],
  sectionLabels: {
    summary: "About Me",
    experience: "Work Experience",
    education: "Education and Training",
    languages: "Language Skills",
    skills: "Digital & Professional Skills",
    interests: "Hobbies and Interests",
    personalDetails: "Additional Information",
    declaration: "Data Protection Consent",
  },
  references: { mode: "on-request" },
  declarationDefault:
    "I hereby consent to the processing of my personal data included in this CV for the purposes of the recruitment process, in accordance with the GDPR (EU 2016/679).",
  defaultTemplate: "classic",
  tips: [
    "Rate languages on the CEFR scale (A1–C2).",
    "Poland and some other countries expect a GDPR consent clause — clear the text if not needed.",
    "Two pages is the norm; Europass layout is widely accepted.",
  ],
};
