import type { RegionConfig } from "./types";

export const gulf: RegionConfig = {
  id: "gcc",
  name: "Middle East (GCC)",
  flag: "🇦🇪",
  covers: "UAE, Saudi Arabia, Qatar, Kuwait, Oman, Bahrain",
  docName: "CV",
  paper: "A4",
  dateFormat: "MM/YYYY",
  maxPages: 4,
  idealPages: 3,
  languageScale: "descriptive",
  fields: {
    photo: "recommended",
    address: "optional",
    dateOfBirth: "recommended",
    gender: "optional",
    maritalStatus: "recommended",
    nationality: "required",
    religion: "hidden",
    nicNumber: "hidden",
    passportNumber: "optional",
    visaStatus: "recommended",
    workAuthorization: "hidden",
    drivingLicense: "recommended",
    noticePeriod: "recommended",
  },
  fieldNotes: {
    visaStatus: "e.g. \"Employment visa – transferable\", \"Visit visa until 03/2027\".",
    drivingLicense: "A valid GCC driving licence is a strong advantage.",
  },
  sections: [
    "summary",
    "personalDetails",
    "experience",
    "education",
    "skills",
    "certifications",
    "languages",
    "projects",
    "references",
  ],
  sectionLabels: {
    summary: "Professional Summary",
    experience: "Professional Experience",
  },
  references: { mode: "full", min: 0 },
  defaultTemplate: "modern",
  tips: [
    "Nationality, visa status and availability (notice period) are screened first.",
    "A professional photo is expected.",
    "Mention a GCC driving licence if you hold one.",
    "List Arabic and English proficiency.",
  ],
};
