import type { RegionConfig } from "./types";

export const international: RegionConfig = {
  id: "intl",
  name: "International / Other",
  flag: "🌍",
  covers: "Neutral format for any country or multinational employers",
  docName: "CV",
  paper: "A4",
  dateFormat: "MMM YYYY",
  maxPages: 3,
  idealPages: 2,
  languageScale: "descriptive",
  fields: {
    photo: "optional",
    address: "hidden",
    dateOfBirth: "hidden",
    gender: "hidden",
    maritalStatus: "hidden",
    nationality: "optional",
    religion: "hidden",
    nicNumber: "hidden",
    passportNumber: "hidden",
    visaStatus: "hidden",
    workAuthorization: "optional",
    drivingLicense: "optional",
    noticePeriod: "optional",
  },
  sections: [
    "summary",
    "experience",
    "education",
    "skills",
    "languages",
    "certifications",
    "projects",
    "interests",
    "personalDetails",
    "references",
  ],
  sectionLabels: {
    summary: "Profile",
    personalDetails: "Additional Information",
  },
  references: { mode: "on-request" },
  defaultTemplate: "classic",
  tips: [
    "A neutral, two-page format works for most multinational employers.",
    "Leave out sensitive personal data unless the employer asks for it.",
  ],
};
