import type { RegionConfig } from "./types";

export const latinAmerica: RegionConfig = {
  id: "latam",
  name: "Latin America",
  flag: "🇧🇷",
  covers: "Mexico, Brazil, Argentina, Colombia, Chile, Peru and others",
  docName: "Currículum Vitae",
  paper: "A4",
  dateFormat: "MM/YYYY",
  maxPages: 3,
  idealPages: 2,
  languageScale: "descriptive",
  fields: {
    photo: "recommended",
    address: "optional",
    dateOfBirth: "optional",
    gender: "hidden",
    maritalStatus: "optional",
    nationality: "optional",
    religion: "hidden",
    nicNumber: "hidden",
    passportNumber: "hidden",
    visaStatus: "hidden",
    workAuthorization: "optional",
    drivingLicense: "optional",
    noticePeriod: "hidden",
  },
  sections: [
    "summary",
    "personalDetails",
    "experience",
    "education",
    "skills",
    "languages",
    "certifications",
    "projects",
    "references",
  ],
  sectionLabels: {
    summary: "Professional Profile",
  },
  references: { mode: "on-request" },
  defaultTemplate: "modern",
  tips: [
    "A photo and basic personal data are common.",
    "Highlight English (or Spanish/Portuguese) level clearly.",
    "Two pages is typical.",
  ],
};
