import type { RegionConfig } from "./types";

export const sriLanka: RegionConfig = {
  id: "lk",
  name: "Sri Lanka",
  flag: "🇱🇰",
  covers: "Sri Lanka (private & government sector)",
  docName: "Curriculum Vitae",
  paper: "A4",
  dateFormat: "MM/YYYY",
  maxPages: 4,
  idealPages: 3,
  languageScale: "descriptive",
  fields: {
    photo: "optional",
    address: "recommended",
    dateOfBirth: "recommended",
    gender: "optional",
    maritalStatus: "optional",
    nationality: "recommended",
    religion: "optional",
    nicNumber: "recommended",
    passportNumber: "optional",
    visaStatus: "hidden",
    workAuthorization: "hidden",
    drivingLicense: "optional",
    noticePeriod: "optional",
  },
  sections: [
    "summary",
    "personalDetails",
    "education",
    "schoolExams",
    "experience",
    "skills",
    "languages",
    "certifications",
    "projects",
    "interests",
    "references",
    "declaration",
  ],
  sectionLabels: {
    summary: "Career Objective",
    schoolExams: "G.C.E. Examinations",
    education: "Higher Education",
    experience: "Work Experience",
    interests: "Extra-Curricular Activities",
    references: "Non-Related Referees",
  },
  references: {
    mode: "full",
    min: 2,
    note: "Sri Lankan employers expect two non-related referees (e.g. a lecturer and a former manager).",
  },
  declarationDefault:
    "I do hereby certify that the above particulars furnished by me are true and accurate to the best of my knowledge.",
  defaultTemplate: "classic",
  tips: [
    "List your G.C.E. O/L and A/L results with subjects and grades — employers check them.",
    "Include your NIC number and full postal address.",
    "Add two non-related referees with contact numbers.",
    "End with a signed declaration, place and date.",
  ],
};
