import type { RegionConfig } from "./types";

const equalityNote = "Not included on UK CVs — employers avoid it under the Equality Act 2010.";

export const uk: RegionConfig = {
  id: "uk",
  name: "United Kingdom & Ireland",
  flag: "🇬🇧",
  covers: "UK, Ireland",
  docName: "CV",
  paper: "A4",
  dateFormat: "MMM YYYY",
  maxPages: 3,
  idealPages: 2,
  languageScale: "descriptive",
  fields: {
    photo: "hidden",
    address: "hidden",
    dateOfBirth: "hidden",
    gender: "hidden",
    maritalStatus: "hidden",
    nationality: "hidden",
    religion: "hidden",
    nicNumber: "hidden",
    passportNumber: "hidden",
    visaStatus: "hidden",
    workAuthorization: "optional",
    drivingLicense: "optional",
    noticePeriod: "optional",
  },
  fieldNotes: {
    photo: equalityNote,
    dateOfBirth: equalityNote,
    gender: equalityNote,
    maritalStatus: equalityNote,
    religion: equalityNote,
    nationality: "Mention your right to work in the UK instead.",
    address: "Only your town/city is needed.",
  },
  sections: [
    "summary",
    "experience",
    "education",
    "skills",
    "certifications",
    "projects",
    "languages",
    "interests",
    "personalDetails",
    "references",
  ],
  sectionLabels: {
    summary: "Personal Profile",
    experience: "Work Experience",
    personalDetails: "Additional Information",
  },
  references: { mode: "on-request" },
  defaultTemplate: "classic",
  tips: [
    "Keep it to two pages of A4.",
    "No photo, date of birth or marital status.",
    "Open with a 3–4 line personal profile tailored to the job.",
    "Use achievement-focused bullet points with numbers where possible.",
  ],
};
